config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :restaurants, only: [:index, :show, :destroy]

  resources :users, only: [:show]

  resources :chats, only: [:create]
  resources :chats, only: [:show] do
    resources :messages, only: [:create]
    patch "restaurants", to: "restaurants#update"
  end

  resources :profils, only: [:create]
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages
  has_many :restaurants
  belongs_to :user
  DEFAULT_TITLE = "New chat"
  TITLE_PROMPT = <<~PROMPT
  Generate a short, descriptive, 3-to-6-word title that tell : Search a restaurant in (location).
  PROMPT
  def generate_title_from_first_message
  return unless title == DEFAULT_TITLE

  first_user_message = messages.where(role: "user").order(:created_at).first
  return if first_user_message.nil?

  response = RubyLLM.chat.with_instructions(TITLE_PROMPT).ask(first_user_message.content)
  update(title: response.content)
end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def create
  @chat = Chat.new(title: "New chat")
  @chat.user = current_user
    if @chat.save
        @chat.messages.create(content:"Welcome to FindYourRestaurant, please give your location", role: "assistant")
        redirect_to chat_path(@chat)
    else
        render "challenges/show"
    end
  end

  def show
    @chat = current_user.chats.find(params[:id])
    @label = label
    @message = Message.new
    @restaurants = @chat.restaurants.last(6)
  end

  private

  def label
    case @chat.messages.where(role:"user").count
    when 0
      "Send your location"
    when 1
      "Send the type of food"
    when 2
      "Send your budget"
    end
  end

end

app/views/chats/show.html.erb
<header> <%= render "shared/navbar" %> </header>

<div class ="text-center">
  <h1 id="chat_title"><%= @chat.title %></h1>
</div>

<div class = "container" >
  <div class = "row d-flex">
    <div id = "chatbox" class ="col-md-6 border" data-controller="chat" data-chat-message-count-value= "<%= @chat.messages.where(role: "user").count%>" >

      <div id="messages">
        <% @chat.messages.each do |message| %>
          <% if message.role == "user" %>
            <div class="d-flex justify-content-end mb-2">
              <div class="px-3 pb-0 pt-3 chat-border">
                <%= simple_format(message.content) %>
              </div>
            </div>
          <% elsif message.role == "assistant" %>
            <div class="d-flex justify-content-start mb-5">
              <div class="px-3 pb-0 pt-3 reponse-ia">
                <%= simple_format(message.content) %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <div id="new_message_container">
        <%= simple_form_for [@chat, @message] do |f| %>
          <%= f.input :content, label: @label, required: true, placeholder: @label %>
          <%= f.button :submit, 'Send', class:"button-perso my-2", style: "width: 150px", data:{chat_target: "button"}%>
        <% end %>
      </div>
    </div>

    <div id="cardandmap" class = "col-md-6" data-controller ="map"  data-map-markers-value="<%= @restaurants.map { |restaurant|
       { lng: restaurant.longitude, lat: restaurant.latitude, name: restaurant.name }
     }.to_json %>">
      <div id = "card">
        <% if @restaurants %>
          <form action="<%= chat_restaurants_path(@chat) %>"  method="patch">
          <ul style="padding: 0px"> <% @restaurants.each do |restaurant| %>
            <li class= "card">
              <div class="card-product">
                <div class="img-block">
                  <%= image_tag restaurant.photo_url, alt: "restau_poster" %>
                </div>
                <div class="card-product-infos">
                  <div class="card-content-text">
                    <h2><%= restaurant.name %></h2>
                    <h4><%= restaurant.category %></h4>
                    <p> <%= restaurant.address %></p>
                    </div>
                    <div class="card-content-numbers">
                    <p><i class="fa-regular fa-star"></i> <%= restaurant.rating %></p>
                    <input type="checkbox"
                          class="card-check"
                          name="restaurant_ids[]"
                          value="<%= restaurant.id %>">
                    <p><%= restaurant.budget %></p>
                  </div>
                </div>
              </div>
            </li>
            <% end %>
          </ul>
          <% if @restaurants.present? %>
            <button type="submit" class="button-perso my-2" style= "width: 300px">Add to favourites</button>
            <button  type="button" style= "width: 300px" class="button-perso my-2" data-action="click->map#displayMap">Display the map</button>
          <% end %>
        </form>
        <% end %>
        </div>
        <div>
        <div id="map" data-map-target="map" style="height: 400px"; display: none></div>
          <script src="https://api.mapbox.com/mapbox-gl-js/v3.16.0/mapbox-gl.js"></script>

        </div>
  </div>
</div>
</div>
<footer> <%= render "shared/footer" %> </footer>