config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :restaurants, only: [:index, :show, :destroy]

  resources :users, only: [:show]

  resources :chats, only: [:create]
  resources :chats, only: [:show] do
    resources :messages, only: [:create]
    patch "restaurants", to: "restaurants#update"
  end

  resources :profils, only: [:create]
end

app/views/pages/home.html.erb
<header> <%= render "shared/navbar" %> </header>

<div class="home-body" >

  <div class="profile favourite-generator" style="width: 90%; margin: auto; margin-bottom:40px" >
    <h1> Welcome <%= current_user.name.capitalize %></h1>
    <p style="width: 95%; margin:auto"><%= @my_profile %></p>
    <%= button_to "Who am I ?",
      profils_path(current_user),
      method: :post,
      class:"button-perso-secondary my-2",
      style: "width: 150px" %>
  </div>

  <div class="home-split" style="width: 90%; margin:auto">

    <div class="card-holder">
      <h3>Your favourite restaurants</h3>
      <%= button_to "Add a new restaurant",
        chats_path,
        method: :post,
        class:"button-perso my-2",
        style: "width: 400px" %>

      <div class="card-scroll">
        <ul style="padding: 0px"> <% @restaurants.each do |restaurant| %>
          <li class= "card">
            <div class="card-product">
              <div class="img-block">
                <%= image_tag(restaurant.photo_url.presence || "burger.jpeg", alt: "restau_poster") %>
                <%= link_to " ", restaurant_path(restaurant), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"},  class:"fa-regular fa-circle-xmark delete-icon" %>
                  </div>
                  <div class="card-product-infos">
                    <div class="card-content-text">
                      <h2><%= restaurant.name %></h2>
                      <h4><%= restaurant.category %></h4>
                      <p> <%= restaurant.address %></p>
                      </div>
                    <div class="card-content-numbers">
                  <p><i class="fa-regular fa-star"></i> <%= restaurant.rating %></p>
                  <p><%= restaurant.budget %></p>
                </div>
              </div>
            </div>
          </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="favourite-generator">
      <div data-controller ="favoritemap" style="width: 80%; margin:auto" data-favoritemap-markers-value="<%= @restaurants.map { |restaurant|
        { lng: restaurant.longitude, lat: restaurant.latitude, name: restaurant.name }
        }.to_json %>">

        <div>
          <% if @restaurants.any? %>
          <div id="map" data-favoritemap-target="map" style="height: 400px"></div>
          <script src="https://api.mapbox.com/mapbox-gl-js/v3.16.0/mapbox-gl.js"></script>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

<footer> <%= render "shared/footer" %> </footer>